# Standalone build for the published repo. Generated by
# tangled/publish/gen-flakes.nu; edit that template, not this file.
#
# Deliberately not the monorepo's default.nix, which is a flakelight module
# the root flake imports and which reaches for ../../nix/lib, so it means
# nothing in a clone. This builds from plain nixpkgs instead.
{
  description = "An xz-compatible LZMA compression tool written in Rust";

  # Pinned to the same revision the monorepo resolves, so every published
  # repo builds against identical nixpkgs and they cannot drift apart. Change
  # it by re-running the generator after a monorepo flake update, never here.
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/fcb8fcd6bf2d0adecae5bd491afaaaf8311b758d";

  outputs = {
    self,
    nixpkgs,
  }: let
    systems = ["x86_64-linux" "aarch64-linux" "aarch64-darwin"];
    forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

    # Read the crate's own manifest rather than restating it here. A workspace
    # root has no [package], and baseNameOf ./. would give the store path, so
    # the repo name is baked in as the fallback.
    cargoToml = builtins.fromTOML (builtins.readFile ./Cargo.toml);
    package = cargoToml.package or {};
    pname = package.name or "rust-xz";
    version = package.version or "0.1.0";
  in {
    packages = forAllSystems (pkgs: {
      ${pname} = pkgs.rustPlatform.buildRustPackage {
        inherit pname version;
        src = ./.;
        cargoLock = {
          lockFile = ./Cargo.lock;
          allowBuiltinFetchGit = true;
        };

        meta = {
          description = "An xz-compatible LZMA compression tool written in Rust";
          license = pkgs.lib.licenses.mit;
        };
      };
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.${pname};
    });

    devShells = forAllSystems (pkgs: {
      default = pkgs.mkShell {
        inputsFrom = [self.packages.${pkgs.stdenv.hostPlatform.system}.${pname}];
        packages = with pkgs; [cargo rustc rust-analyzer clippy rustfmt];
      };
    });

    checks = forAllSystems (pkgs: {
      build = self.packages.${pkgs.stdenv.hostPlatform.system}.${pname};
    });

    formatter = forAllSystems (pkgs: pkgs.alejandra);
  };
}
